import type { Metadata } from 'next';
import Footer from './_components/footer';
import Nav from './_components/nav';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Nav />

      <main className='z-[1] flex flex-1 flex-col'>{children}</main>

      <Footer />
    </>
  );
}
